### PR TITLE
button color fix

### PR DESCRIPTION
**Pull request by samanthatuhseng**
## Description

Changing button color fix according to figma design.

## Other considerations

Screenshot 2023-11-14 at 2 27 06 PM
Screenshot 2023-11-14 at 2 29 15 PM

### CODE REVIEW

**Review by DonaldKLee — CHANGES_REQUESTED** [review]
lgtm

minor fix
- make text in button on 1 line
e.g
image

**Comment by DonaldKLee** [comment]
> lgtm
> 
> minor fix
> 
> * make text in button on 1 line
>   e.g
>   image

image

**Comment by samanthatuhseng** [comment]
Screenshot 2023-11-14 at 2 42 27 PM
Here you go Donald.

**Comment by DonaldKLee** [comment]
> Screenshot 2023-11-14 at 2 42 27 PM Here you go Donald.

Great job Sam. Very proud of your achievement :)

**Review by DonaldKLee — APPROVED** [review]

**Pull request merged**
