### PR TITLE
Escape Node v16

### PR DESCRIPTION
**Pull request by lsha0730**
- Upgraded react-scripts
- Dealt with no anonymous default exports error

### CODE REVIEW

**Comment by meleongg** [comment]
Does it work if you remove our node 16 and firebase-tools band-aid fixes to the github ci cd workflow files (.github/workflows)?

**Comment by lsha0730** [comment]
@meleongg Are the bandaid fixes the forced old version numbers in the workflow files? The preview seems to work fine after removing the versions, but lmk if I removed the band-aid properly

**Comment by meleongg** [comment]
Yup, the band-aid fixes are the hardcoded version numbers

**Comment by meleongg** [comment]
We'll prolly merge this one after cmd-f in case there's something bad that happens LOL

**Review by meleongg — APPROVED** [review]
Let's hope this doesn't break anything :D

**Pull request merged**
