### PR TITLE
Hackcamp2023 reskin

### PR DESCRIPTION
**Pull request by DonaldKLee**
Made changes to the colours, updated the login page, and replaced nwHacks content with HackCamp
- gradients and floating images will be added later

Before merging, see Slack message on nwHacks 2024 vs HackCamp 2023 portal conflicts

### CODE REVIEW

**Comment by DonaldKLee** [comment]
> Made changes to the colours, updated the login page, and replaced nwHacks content with HackCamp
> 
> * gradients and floating images will be added later
> 
> Before merging, see Slack message on nwHacks 2024 vs HackCamp 2023 portal conflicts

save qr code to pdf is implemented now

**Comment by meleongg** [comment]
Good work Donald! The save PDF feature looks great on desktop! 

mobile view of save PDF looks a little too wide - @DonaldKLee were you able to find a workaround for this?
image

the saved PDF also looks a little blurry:
image

**Comment by meleongg** [comment]
@DonaldKLee could we fixed the /application/closed route 

image

**Review by meleongg — APPROVED** [review]
lgtm

**Pull request merged**
