### PR TITLE
Reskinned Portal

### PR DESCRIPTION
**Pull request by DonaldKLee**
Everything should look exactly like what's on the Figma file! (hopefully)
Only thing missing are the gradient borders for the primary and secondary buttons, ~~no one will notice right? 👀~~  will look into how to make those soon! :))

### CODE REVIEW

**Comment by naijwu** [comment]
This button contrast looks a bit sus

image

**Comment by DonaldKLee** [comment]
> This button contrast looks a bit sus
> 
> image

LOL oops, used wrong colours, should be good now!

**Comment by kozr** [comment]
image
 The color and the borders are different
image

**Comment by kozr** [comment]
- Button colors
- Textbox placeholder texts should be bolded

**Review by anson1014 — APPROVED** [review]

**Comment by anson1014** [comment]
lgtm

**Pull request merged**
