### PR TITLE
Vite migration

### PR DESCRIPTION
**Pull request by martincai8**
- completed CRA -> vite
- standardized yarn across the repo (updated hosting file and added `yarn.lock` back)
- cleaned up some of the imports

### CODE REVIEW

**Review by tdanielles — APPROVED** [review]
lgtm :D

**Review by DonaldKLee — APPROVED** [review]
lgtm! might be placebo, but load time has significantly increased! Great job!

**Comment by martincai8** [comment]
@DonaldKLee idk if that's a good thing LOL

**Comment by DonaldKLee** [comment]
> @DonaldKLee idk if that's a good thing LOL

OH DECREASED, MB. I MEANT IT LOADS FASTER NOW 💀

**Pull request merged**
