### PR TITLE
Portal UI changes

### PR DESCRIPTION
**Pull request by samanthatuhseng**
## Description

Reskin for cmdf 2024 portal. Changed theme colours, QR ticket visual and home background.

## Other considerations

Planned future changes: schedule visual bug of horizontal overlapping events.

### CODE REVIEW

**Comment by samanthatuhseng** [comment]
ticket reference:
Screenshot 2024-02-25 at 3 17 08 PM

**Comment by samanthatuhseng** [comment]
mobile ticket reference:

**Comment by meleongg** [comment]
sorry @samanthatuhseng I think my changes caused some merge conflicts on your side

**Review by meleongg — APPROVED** [review]
looks hella nice! ty sam!

**Pull request merged**
